"""Initial migration

Revision ID: 05b006232891
Revises: 
Create Date: 2026-01-02 18:40:17.653646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05b006232891'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password_digest', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'SUPER_ADMIN', name='administratorrole'), nullable=False),
    sa.Column('first_login', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_administrators_id'), 'administrators', ['id'], unique=False)
    op.create_index(op.f('ix_administrators_name'), 'administrators', ['name'], unique=True)
    op.create_index(op.f('ix_administrators_role'), 'administrators', ['role'], unique=False)
    op.create_table('ct_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('dicom_series', sa.Text(), nullable=True),
    sa.Column('dicom_file', sa.String(), nullable=True),
    sa.Column('study_date', sa.Date(), nullable=True),
    sa.Column('modality', sa.String(), nullable=False),
    sa.Column('slice_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'COMPLETED', 'FAILED', name='ctscanstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ct_scans_id'), 'ct_scans', ['id'], unique=False)
    op.create_index(op.f('ix_ct_scans_patient_id'), 'ct_scans', ['patient_id'], unique=False)
    op.create_table('admin_oplogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('administrator_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['administrator_id'], ['administrators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_admin_oplogs_action'), 'admin_oplogs', ['action'], unique=False)
    op.create_index(op.f('ix_admin_oplogs_administrator_id'), 'admin_oplogs', ['administrator_id'], unique=False)
    op.create_index(op.f('ix_admin_oplogs_id'), 'admin_oplogs', ['id'], unique=False)
    op.create_table('segmentation_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ct_scan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='segmentationtaskstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('inference_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ct_scan_id'], ['ct_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segmentation_tasks_ct_scan_id'), 'segmentation_tasks', ['ct_scan_id'], unique=False)
    op.create_index(op.f('ix_segmentation_tasks_id'), 'segmentation_tasks', ['id'], unique=False)
    op.create_table('three_d_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ct_scan_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model_file', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='threedmodelstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ct_scan_id'], ['ct_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_three_d_models_id'), 'three_d_models', ['id'], unique=False)
    op.create_table('segmentation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segmentation_task_id', sa.Integer(), nullable=False),
    sa.Column('mask_file', sa.String(), nullable=True),
    sa.Column('contours', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('volume_ml', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dice_coefficient', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('iou_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['segmentation_task_id'], ['segmentation_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segmentation_results_id'), 'segmentation_results', ['id'], unique=False)
    op.create_index(op.f('ix_segmentation_results_segmentation_task_id'), 'segmentation_results', ['segmentation_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segmentation_results_segmentation_task_id'), table_name='segmentation_results')
    op.drop_index(op.f('ix_segmentation_results_id'), table_name='segmentation_results')
    op.drop_table('segmentation_results')
    op.drop_index(op.f('ix_three_d_models_id'), table_name='three_d_models')
    op.drop_table('three_d_models')
    op.drop_index(op.f('ix_segmentation_tasks_id'), table_name='segmentation_tasks')
    op.drop_index(op.f('ix_segmentation_tasks_ct_scan_id'), table_name='segmentation_tasks')
    op.drop_table('segmentation_tasks')
    op.drop_index(op.f('ix_admin_oplogs_id'), table_name='admin_oplogs')
    op.drop_index(op.f('ix_admin_oplogs_administrator_id'), table_name='admin_oplogs')
    op.drop_index(op.f('ix_admin_oplogs_action'), table_name='admin_oplogs')
    op.drop_table('admin_oplogs')
    op.drop_index(op.f('ix_ct_scans_patient_id'), table_name='ct_scans')
    op.drop_index(op.f('ix_ct_scans_id'), table_name='ct_scans')
    op.drop_table('ct_scans')
    op.drop_index(op.f('ix_administrators_role'), table_name='administrators')
    op.drop_index(op.f('ix_administrators_name'), table_name='administrators')
    op.drop_index(op.f('ix_administrators_id'), table_name='administrators')
    op.drop_table('administrators')
    # ### end Alembic commands ###

